### ISSUE TITLE
If user has only one github account, integrate does nothing

### ISSUE THREAD

**Issue by quickhand** [associatedpress/datakit-github#15]
* datakit-github version: 0.1.0
* Python version: 3.7.4
* Operating System: macOs 10.13.6

### Description

If the user only has a single account on github, datakit github integrate returns immediately to the terminal with no output, and does not initialize the repository

The heart of the problem is the following code in integrate.py:

```python
accounts = GithubApi.accounts(api_key)
    # Prompt user to select an account.
    if len(accounts) == 1:
        account = accounts[0]
    else:
        msg = "Choose an account where the new project should be created:\n"
```
The repo initialization happens entirely in this else branch. So if len(accounts) == 1, nothing happens, and datakit github integrate simply quits.

**Comment by zstumgoren** [comment]
Fix applied. Please re-open if you encounter issues. And thanks again for reporting!
