### ISSUE TITLE
Create more robust solution for nudging "master" to "main"  during repo initialization

### ISSUE THREAD

**Issue by zstumgoren** [associatedpress/datakit-github#26]
Details on options are nicely spelled out [here](https://github.com/associatedpress/datakit-gitlab/pull/8#issuecomment-963606340) by @myersjustinc. 

We'll wait on the datakit-github implementation until we've settled on a strategy over on datakit-gitlab, so the two plugins can mirror each other.

**Comment by myersjustinc** [comment]
As promised, here's how that all went down in `datakit-gitlab`:  
<https://github.com/associatedpress/datakit-gitlab/pull/8/files>
